"use client"

import React, { createContext, useContext, useMemo, useState, useEffect } from "react"

export type LanguageCode = "en" | "fr" | "es" | "de"

type Dictionary = Record<string, string>

const dictionaries: Record<LanguageCode, Dictionary> = {
  en: {
    home: "Home",
    transfer: "Transfer",
    rewards: "Rewards",
    pay: "Pay",
    account: "Account",
    group_pay: "Group Pay",
    profile: "Profile",
    settings: "Settings",
    request: "Request",
    recipients: "Recipients",
    onramp: "On/Off Ramp",
    connect_wallet: "Connect Wallet",
    sending_to: "Sending to",
    amount: "Amount",
    token: "Token",
    memo: "Memo",
    pay_now: "Pay Now",
    build_payment_link: "Build Payment Link",
    generate_link: "Generate Link",
    copy_link: "Copy Link",
    saved_recipients: "Saved Recipients",
    add_recipient: "Add Recipient",
    name: "Name",
    wallet_address: "Wallet Address",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    // hero
    hero_title: "Send Money Across Borders",
    hero_subtitle: "Fast, secure, and affordable remittance service powered by blockchain. Earn cashback and referral rewards on every transaction.",
    cta_get_started: "Get Started",
    cta_learn_more: "Learn More",
    stat_fee_label: "Transfer Fee",
    stat_cashback_label: "Cashback",
    stat_available_label: "Available",
    hero_network_label: "Global Remittance Network",
    // features
    features_title: "Powerful Features",
    features_subtitle: "Everything you need for seamless cross-border remittance",
    feat_fast_title: "Lightning Fast",
    feat_fast_desc: "Send money in seconds with blockchain-powered transfers",
    feat_cashback_title: "Cashback Rewards",
    feat_cashback_desc: "Earn 1% cashback on transactions over $1,000",
    feat_referral_title: "Referral Program",
    feat_referral_desc: "Earn 0.5% on every transaction from your referrals",
    feat_batch_title: "Batch Transfers",
    feat_batch_desc: "Upload CSV files to send multiple remittances at once",
    feat_tracking_title: "Real-time Tracking",
    feat_tracking_desc: "Monitor your transfers with live transaction updates",
    feat_secure_title: "Secure & Transparent",
    feat_secure_desc: "Smart contract verified transactions on Base Sepolia",
    // rewards
    rewards_title: "Earn While You Send",
    rewards_subtitle: "Multiple ways to maximize your earnings on RemitFlow",
    cashback: "Cashback",
    referrals: "Referrals",
    volume_bonus: "Volume Bonus",
    cashback_desc: "Earn 1% cashback on all transactions over $1,000",
    referrals_desc: "Earn 0.5% on every transaction from your referrals",
    volume_bonus_desc: "Unlock higher rewards as you increase your transaction volume",
    // transfer form
    label_recipient_wallet: "Recipient Wallet Address",
    label_amount: "Amount",
    label_payment_currency: "Payment Currency",
    label_destination_country: "Destination Country",
    label_recipient_currency: "Recipient Currency",
    label_description_optional: "Description (Optional)",
    breakdown_amount: "Amount",
    breakdown_fee: "Transfer Fee (0.5%)",
    breakdown_cashback: "Cashback (1%)",
    breakdown_total: "Total to Send",
    btn_send_remittance: "Send Remittance",
    processing: "Processing...",
    quick_pick_recipient: "Quick Pick Recipient",
    select_saved_recipient: "Select from saved recipients",
  },
  fr: {
    home: "Accueil",
    transfer: "Transfert",
    rewards: "Récompenses",
    pay: "Payer",
    account: "Compte",
    group_pay: "Paiement de groupe",
    profile: "Profil",
    settings: "Paramètres",
    request: "Demande",
    recipients: "Bénéficiaires",
    onramp: "On/Off Ramp",
    connect_wallet: "Connecter le portefeuille",
    sending_to: "Envoi à",
    amount: "Montant",
    token: "Token",
    memo: "Note",
    pay_now: "Payer",
    build_payment_link: "Créer un lien de paiement",
    generate_link: "Générer le lien",
    copy_link: "Copier le lien",
    saved_recipients: "Bénéficiaires enregistrés",
    add_recipient: "Ajouter",
    name: "Nom",
    wallet_address: "Adresse du portefeuille",
    save: "Enregistrer",
    cancel: "Annuler",
    edit: "Modifier",
    delete: "Supprimer",
    hero_title: "Envoyer de l'argent à travers les frontières",
    hero_subtitle: "Service de transfert rapide, sécurisé et abordable. Gagnez du cashback et des récompenses de parrainage.",
    cta_get_started: "Commencer",
    cta_learn_more: "En savoir plus",
    stat_fee_label: "Frais de transfert",
    stat_cashback_label: "Cashback",
    stat_available_label: "Disponible",
    hero_network_label: "Réseau de remise mondial",
    features_title: "Fonctionnalités puissantes",
    features_subtitle: "Tout ce dont vous avez besoin pour des envois transfrontaliers fluides",
    feat_fast_title: "Ultra rapide",
    feat_fast_desc: "Envoyez en quelques secondes avec la blockchain",
    feat_cashback_title: "Récompenses cashback",
    feat_cashback_desc: "Gagnez 1% au-delà de 1 000 $",
    feat_referral_title: "Parrainage",
    feat_referral_desc: "Gagnez 0,5% sur les transactions de vos filleuls",
    feat_batch_title: "Transferts groupés",
    feat_batch_desc: "Envoyez plusieurs remises via CSV",
    feat_tracking_title: "Suivi en temps réel",
    feat_tracking_desc: "Suivez vos transferts en direct",
    feat_secure_title: "Sécurisé et transparent",
    feat_secure_desc: "Contrats intelligents vérifiés sur Base Sepolia",
    rewards_title: "Gagnez en envoyant",
    rewards_subtitle: "Multipliez vos gains avec RemitFlow",
    cashback: "Cashback",
    referrals: "Parrainages",
    volume_bonus: "Bonus de volume",
    cashback_desc: "1% de cashback au-delà de 1 000 $",
    referrals_desc: "0,5% sur chaque transaction de vos filleuls",
    volume_bonus_desc: "Débloquez plus en augmentant votre volume",
    label_recipient_wallet: "Adresse du portefeuille",
    label_amount: "Montant",
    label_payment_currency: "Devise de paiement",
    label_destination_country: "Pays de destination",
    label_recipient_currency: "Devise du destinataire",
    label_description_optional: "Description (facultatif)",
    breakdown_amount: "Montant",
    breakdown_fee: "Frais de transfert (0,5%)",
    breakdown_cashback: "Cashback (1%)",
    breakdown_total: "Total à envoyer",
    btn_send_remittance: "Envoyer",
    processing: "Traitement...",
    quick_pick_recipient: "Choisir un bénéficiaire",
    select_saved_recipient: "Choisir parmi les bénéficiaires",
  },
  es: {
    home: "Inicio",
    transfer: "Transferir",
    rewards: "Recompensas",
    pay: "Pagar",
    account: "Cuenta",
    group_pay: "Pago en grupo",
    profile: "Perfil",
    settings: "Ajustes",
    request: "Solicitud",
    recipients: "Destinatarios",
    onramp: "On/Off Ramp",
    connect_wallet: "Conectar cartera",
    sending_to: "Enviando a",
    amount: "Cantidad",
    token: "Token",
    memo: "Nota",
    pay_now: "Pagar ahora",
    build_payment_link: "Crear enlace de pago",
    generate_link: "Generar enlace",
    copy_link: "Copiar enlace",
    saved_recipients: "Destinatarios guardados",
    add_recipient: "Añadir",
    name: "Nombre",
    wallet_address: "Dirección de cartera",
    save: "Guardar",
    cancel: "Cancelar",
    edit: "Editar",
    delete: "Eliminar",
    hero_title: "Enviar dinero a través de fronteras",
    hero_subtitle: "Servicio rápido, seguro y asequible. Gana cashback y recompensas por referidos.",
    cta_get_started: "Comenzar",
    cta_learn_more: "Saber más",
    stat_fee_label: "Comisión",
    stat_cashback_label: "Cashback",
    stat_available_label: "Disponible",
    hero_network_label: "Red global de remesas",
    features_title: "Funciones potentes",
    features_subtitle: "Todo para remesas transfronterizas sin fricción",
    feat_fast_title: "Ultrarrápido",
    feat_fast_desc: "Envía en segundos con blockchain",
    feat_cashback_title: "Recompensas de cashback",
    feat_cashback_desc: "Gana 1% en transacciones > $1,000",
    feat_referral_title: "Referidos",
    feat_referral_desc: "Gana 0.5% por las transacciones de tus referidos",
    feat_batch_title: "Transferencias en lote",
    feat_batch_desc: "Envía varias remesas con CSV",
    feat_tracking_title: "Seguimiento en tiempo real",
    feat_tracking_desc: "Monitorea tus transferencias",
    feat_secure_title: "Seguro y transparente",
    feat_secure_desc: "Contratos inteligentes en Base Sepolia",
    rewards_title: "Gana mientras envías",
    rewards_subtitle: "Multiplica tus ganancias con RemitFlow",
    cashback: "Cashback",
    referrals: "Referidos",
    volume_bonus: "Bono por volumen",
    cashback_desc: "1% de cashback en transacciones > $1,000",
    referrals_desc: "0.5% en cada transacción de tus referidos",
    volume_bonus_desc: "Gana más con mayor volumen",
    label_recipient_wallet: "Dirección del destinatario",
    label_amount: "Cantidad",
    label_payment_currency: "Moneda de pago",
    label_destination_country: "País de destino",
    label_recipient_currency: "Moneda del destinatario",
    label_description_optional: "Descripción (opcional)",
    breakdown_amount: "Cantidad",
    breakdown_fee: "Comisión (0.5%)",
    breakdown_cashback: "Cashback (1%)",
    breakdown_total: "Total a enviar",
    btn_send_remittance: "Enviar remesa",
    processing: "Procesando...",
    quick_pick_recipient: "Elegir destinatario",
    select_saved_recipient: "Elegir entre guardados",
  },
  de: {
    home: "Startseite",
    transfer: "Überweisen",
    rewards: "Prämien",
    pay: "Zahlen",
    account: "Konto",
    group_pay: "Gruppenüberweisung",
    profile: "Profil",
    settings: "Einstellungen",
    request: "Anfrage",
    recipients: "Empfänger",
    onramp: "On/Off Ramp",
    connect_wallet: "Wallet verbinden",
    sending_to: "Senden an",
    amount: "Betrag",
    token: "Token",
    memo: "Notiz",
    pay_now: "Jetzt bezahlen",
    build_payment_link: "Zahlungslink erstellen",
    generate_link: "Link generieren",
    copy_link: "Link kopieren",
    saved_recipients: "Gespeicherte Empfänger",
    add_recipient: "Hinzufügen",
    name: "Name",
    wallet_address: "Wallet-Adresse",
    save: "Speichern",
    cancel: "Abbrechen",
    edit: "Bearbeiten",
    delete: "Löschen",
    hero_title: "Geld grenzüberschreitend senden",
    hero_subtitle: "Schneller, sicherer und günstiger Service. Verdiene Cashback und Empfehlungsprämien.",
    cta_get_started: "Loslegen",
    cta_learn_more: "Mehr erfahren",
    stat_fee_label: "Gebühr",
    stat_cashback_label: "Cashback",
    stat_available_label: "Verfügbar",
    hero_network_label: "Globales Remittance-Netzwerk",
    features_title: "Leistungsstarke Funktionen",
    features_subtitle: "Alles für reibungslose Auslandsüberweisungen",
    feat_fast_title: "Blitzschnell",
    feat_fast_desc: "Sende in Sekunden per Blockchain",
    feat_cashback_title: "Cashback-Prämien",
    feat_cashback_desc: "1% Cashback über 1.000 $",
    feat_referral_title: "Empfehlungen",
    feat_referral_desc: "0,5% auf Transaktionen deiner Referrals",
    feat_batch_title: "Sammelüberweisungen",
    feat_batch_desc: "Mehrere Überweisungen via CSV",
    feat_tracking_title: "Echtzeit-Tracking",
    feat_tracking_desc: "Beobachte deine Transfers live",
    feat_secure_title: "Sicher & transparent",
    feat_secure_desc: "Verifizierte Smart Contracts auf Base Sepolia",
    rewards_title: "Verdiene beim Senden",
    rewards_subtitle: "Mehr Ertrag mit RemitFlow",
    cashback: "Cashback",
    referrals: "Empfehlungen",
    volume_bonus: "Volumenbonus",
    cashback_desc: "1% Cashback über 1.000 $",
    referrals_desc: "0,5% auf jede Referral-Transaktion",
    volume_bonus_desc: "Mehr Bonus mit höherem Volumen",
    label_recipient_wallet: "Wallet-Adresse des Empfängers",
    label_amount: "Betrag",
    label_payment_currency: "Zahlungswährung",
    label_destination_country: "Zielland",
    label_recipient_currency: "Währung des Empfängers",
    label_description_optional: "Beschreibung (optional)",
    breakdown_amount: "Betrag",
    breakdown_fee: "Überweisungsgebühr (0,5%)",
    breakdown_cashback: "Cashback (1%)",
    breakdown_total: "Zu sendender Gesamtbetrag",
    btn_send_remittance: "Überweisung senden",
    processing: "Wird verarbeitet...",
    quick_pick_recipient: "Empfänger wählen",
    select_saved_recipient: "Aus gespeicherten wählen",
  },
}

type LanguageContextValue = {
  lang: LanguageCode
  setLang: (l: LanguageCode) => void
  t: (key: keyof typeof dictionaries["en"]) => string
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<LanguageCode>("en")

  useEffect(() => {
    const stored = typeof window !== "undefined" ? (localStorage.getItem("lang") as LanguageCode | null) : null
    if (stored) setLang(stored)
  }, [])

  const value = useMemo(() => {
    const t = (key: keyof typeof dictionaries["en"]) => dictionaries[lang][key] ?? dictionaries.en[key]
    const setter = (l: LanguageCode) => {
      setLang(l)
      if (typeof window !== "undefined") localStorage.setItem("lang", l)
    }
    return { lang, setLang: setter, t }
  }, [lang])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useI18n() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error("useI18n must be used within LanguageProvider")
  return ctx
}
